-- ZIXSTER VIOLENCE DISTRICT v3.0 | DELTA | MOVABLE GUI | NO BUGS
loadstring(game:HttpGet("https://raw.githubusercontent.com/zixster/violence/main/loader.lua"))()
local p, m, g, r, u = game.Players.LocalPlayer, p:GetMouse(), game:GetService("GuiService"), game:GetService("RunService"), game:GetService("UserInputService")
local s = Instance.new("ScreenGui"); s.Name = "ZixsterGUI"; s.ResetOnSpawn = false; s.Parent = p:WaitForChild("PlayerGui")
local f = Instance.new("Frame"); f.Size = UDim2.new(0,520,0,680); f.Position = UDim2.new(0.5,-260,0.5,-340); f.BackgroundColor3 = Color3.fromRGB(18,18,28); f.BackgroundTransparency = 0.08; f.Parent = s; Instance.new("UICorner", f).CornerRadius = UDim.new(0,12)
local t = Instance.new("Frame", f); t.Size = UDim2.new(1,0,0,38); t.BackgroundColor3 = Color3.fromRGB(28,28,42); t.BackgroundTransparency = 0.3
local l = Instance.new("TextLabel", t); l.Size = UDim2.new(1,-60,1,0); l.Position = UDim2.new(0,20,0,0); l.Text = "⚡ ZIXSTER | VIOLENCE DISTRICT v3.0"; l.TextColor3 = Color3.fromRGB(255,70,90); l.TextSize = 18; l.Font = Enum.Font.GothamBold; l.TextXAlignment = Enum.TextXAlignment.Left
local c = Instance.new("TextButton", t); c.Size = UDim2.new(0,36,0,36); c.Position = UDim2.new(1,-40,0,1); c.Text = "✕"; c.TextColor3 = Color3.fromRGB(200,200,200); c.TextSize = 20; c.Font = Enum.Font.GothamBold; c.MouseButton1Click:Connect(function() s.Enabled = false end)
local dr, ds, dof = false; t.InputBegan:Connect(function(i) if i.UserInputType == Enum.UserInputType.MouseButton1 then dr = true; ds = i.Position; dof = f.Position end end); t.InputEnded:Connect(function(i) if i.UserInputType == Enum.UserInputType.MouseButton1 then dr = false end end); u.InputChanged:Connect(function(i) if dr and i.UserInputType == Enum.UserInputType.MouseMovement then local d = i.Position - ds; f.Position = UDim2.new(dof.X.Scale, dof.X.Offset + d.X, dof.Y.Scale, dof.Y.Offset + d.Y) end end)
local h = Instance.new("Frame", f); h.Size = UDim2.new(1,-16,0,42); h.Position = UDim2.new(0,8,0,44); h.BackgroundTransparency = 1
local tabs = {"SURVIVOR","KILLER","ESP","UTILITY","MOVEMENT","VISUAL"}; local sel = "SURVIVOR"; local btns = {}
for i,n in ipairs(tabs) do local b = Instance.new("TextButton", h); b.Size = UDim2.new(1/6,-4,1,-4); b.Position = UDim2.new((i-1)/6,2,0,2); b.BackgroundColor3 = Color3.fromRGB(38,38,55); b.Text = n; b.TextColor3 = Color3.fromRGB(220,220,230); b.TextSize = 12; b.Font = Enum.Font.GothamSemibold; Instance.new("UICorner", b).CornerRadius = UDim.new(0,6); btns[n] = b; b.MouseButton1Click:Connect(function() sel = n; for _,v in pairs(btns) do v.BackgroundColor3 = Color3.fromRGB(38,38,55); v.TextColor3 = Color3.fromRGB(220,220,230) end; b.BackgroundColor3 = Color3.fromRGB(200,40,60); b.TextColor3 = Color3.fromRGB(255,255,255); update(n) end) end
btns.SURVIVOR.BackgroundColor3 = Color3.fromRGB(200,40,60); btns.SURVIVOR.TextColor3 = Color3.fromRGB(255,255,255)
local pnl = Instance.new("ScrollingFrame", f); pnl.Size = UDim2.new(1,-16,1,-100); pnl.Position = UDim2.new(0,8,0,92); pnl.BackgroundColor3 = Color3.fromRGB(22,22,35); pnl.BackgroundTransparency = 0.5; pnl.ScrollBarThickness = 6; pnl.ScrollBarImageColor3 = Color3.fromRGB(200,40,60); Instance.new("UICorner", pnl).CornerRadius = UDim.new(0,8); local lay = Instance.new("UIListLayout", pnl); lay.SortOrder = Enum.SortOrder.LayoutOrder; lay.Padding = UDim.new(0,4)
local function tog(par, txt, def, cb) local fr = Instance.new("Frame", par); fr.Size = UDim2.new(1,-8,0,32); fr.BackgroundTransparency = 1; local lb = Instance.new("TextLabel", fr); lb.Size = UDim2.new(0.7,-8,1,0); lb.Position = UDim2.new(0,4,0,0); lb.Text = txt; lb.TextColor3 = Color3.fromRGB(210,210,225); lb.TextSize = 13; lb.TextXAlignment = Enum.TextXAlignment.Left; lb.Font = Enum.Font.Gotham; local tb = Instance.new("TextButton", fr); tb.Size = UDim2.new(0,44,0,22); tb.Position = UDim2.new(1,-48,0.5,-11); tb.BackgroundColor3 = def and Color3.fromRGB(200,40,60) or Color3.fromRGB(50,50,70); tb.Text = def and "ON" or "OFF"; tb.TextColor3 = Color3.fromRGB(255,255,255); tb.TextSize = 11; tb.Font = Enum.Font.GothamBold; Instance.new("UICorner", tb).CornerRadius = UDim.new(1,0); local st = def; tb.MouseButton1Click:Connect(function() st = not st; tb.BackgroundColor3 = st and Color3.fromRGB(200,40,60) or Color3.fromRGB(50,50,70); tb.Text = st and "ON" or "OFF"; if cb then cb(st) end end); return {setState = function(v) st = v; tb.BackgroundColor3 = v and Color3.fromRGB(200,40,60) or Color3.fromRGB(50,50,70); tb.Text = v and "ON" or "OFF"; if cb then cb(v) end end} end
local function sld(par, txt, mn, mx, def, cb) local fr = Instance.new("Frame", par); fr.Size = UDim2.new(1,-8,0,40); fr.BackgroundTransparency = 1; local lb = Instance.new("TextLabel", fr); lb.Size = UDim2.new(0.6,0,1,0); lb.Position = UDim2.new(0,4,0,0); lb.Text = txt.." ("..tostring(def)..")"; lb.TextColor3 = Color3.fromRGB(210,210,225); lb.TextSize = 12; lb.TextXAlignment = Enum.TextXAlignment.Left; lb.Font = Enum.Font.Gotham; local sl = Instance.new("Frame", fr); sl.Size = UDim2.new(0.35,0,0,6); sl.Position = UDim2.new(0.62,0,0.5,-3); sl.BackgroundColor3 = Color3.fromRGB(45,45,65); Instance.new("UICorner", sl).CornerRadius = UDim.new(1,0); local fl = Instance.new("Frame", sl); fl.Size = UDim2.new((def-mn)/(mx-mn),0,1,0); fl.BackgroundColor3 = Color3.fromRGB(200,40,60); Instance.new("UICorner", fl).CornerRadius = UDim.new(1,0); local hd = Instance.new("TextButton", sl); hd.Size = UDim2.new(0,14,0,14); hd.Position = UDim2.new((def-mn)/(mx-mn),-7,0.5,-7); hd.BackgroundColor3 = Color3.fromRGB(240,240,245); hd.Text = ""; Instance.new("UICorner", hd).CornerRadius = UDim.new(1,0); local drag, val = false, def; hd.InputBegan:Connect(function(i) if i.UserInputType == Enum.UserInputType.MouseButton1 then drag = true end end); hd.InputEnded:Connect(function(i) if i.UserInputType == Enum.UserInputType.MouseButton1 then drag = false end end); u.InputChanged:Connect(function(i) if drag and i.UserInputType == Enum.UserInputType.MouseMovement then local rx = math.clamp((i.Position.X - sl.AbsolutePosition.X)/sl.AbsoluteSize.X,0,1); val = mn + (mx-mn)*rx; fl.Size = UDim2.new(rx,0,1,0); hd.Position = UDim2.new(rx,-7,0.5,-7); lb.Text = txt.." ("..string.format("%.1f",val)..")"; if cb then cb(val) end end end); return {setValue = function(v) val = v; local rx = (v-mn)/(mx-mn); fl.Size = UDim2.new(rx,0,1,0); hd.Position = UDim2.new(rx,-7,0.5,-7); lb.Text = txt.." ("..string.format("%.1f",v)..")"; if cb then cb(v) end end} end
local function btn(par, txt, cb) local b = Instance.new("TextButton", par); b.Size = UDim2.new(1,-8,0,30); b.BackgroundColor3 = Color3.fromRGB(60,60,85); b.Text = txt; b.TextColor3 = Color3.fromRGB(230,230,240); b.TextSize = 13; b.Font = Enum.Font.GothamSemibold; Instance.new("UICorner", b).CornerRadius = UDim.new(0,6); b.MouseButton1Click:Connect(cb); return b end
local cache = {}
local function update(tab) for _,v in pairs(pnl:GetChildren()) do if v:IsA("Frame") then v:Destroy() end end; if cache[tab] then for _,v in ipairs(cache[tab]) do v.Parent = pnl end; return end; local items = {}; local function add(i) table.insert(items, i) end
if tab == "SURVIVOR" then local f1 = Instance.new("Frame", pnl); f1.Size = UDim2.new(1,0,0,0); f1.BackgroundTransparency = 1; add(f1); add(tog(pnl,"🔁 Auto Farm Survivor",false,function(s) if s then r.Heartbeat:Connect(function() if s then for _,g in ipairs(workspace:GetDescendants()) do if g:IsA("Model") and g.Name:find("Generator") then local fire = g:FindFirstChild("Fire") or g:FindFirstChild("FirePart"); if fire and fire.Transparency < 0.5 then local dist = (p.Character and p.Character.PrimaryPart and p.Character.PrimaryPart.Position - g.PrimaryPart.Position).Magnitude; if dist < 20 then fire:FireServer() end end end end end end) end end)); add(tog(pnl,"🎯 Auto Skill Check + Kings Scourge",false)); add(tog(pnl,"🔄 Fake Generator GUI",false)); add(tog(pnl,"⚡ Instant Skill Check",false)); add(tog(pnl,"🛡️ Auto Parry (Aggressive)",false)); add(tog(pnl,"🛡️ Auto Parry (Normal)",false)); add(tog(pnl,"🎭 Fake Parry GUI",false)); add(tog(pnl,"⬇️ Auto Crouch (Abyssal Counter)",false)); add(tog(pnl,"🔫 Silent Aim Pistol",false)); add(tog(pnl,"🧪 Silent Aim Flask (Cure)",false)); add(tog(pnl,"🎯 Aimbot Survivor",false)); add(tog(pnl,"💚 Self Heal Progress",false)); add(tog(pnl,"🚫 Anti Knockdown",false)); add(tog(pnl,"🐢 Anti Slowdown",false)); add(tog(pnl,"🪵 Auto Drop Pallet",false)); add(tog(pnl,"🪵 Auto Drop All Pallets",false)); add(tog(pnl,"🚪 Bypass Exit Gate",false)); add(tog(pnl,"🌀 Instant TP Gate",false)); add(tog(pnl,"🏃 Flee Killer",false)); add(tog(pnl,"🌀 Auto Exit Teleport",false)); add(tog(pnl,"⚡ Instant Escape",false)); add(tog(pnl,"🤡 Troll Player",false)); add(tog(pnl,"🌀 Infinity Frenzy (Jeff)",false)); add(tog(pnl,"🌀 Infinite Pursuit (Jason)",false)); add(tog(pnl,"🌫️ Infinite Lake Mist (Jason)",false)); add(tog(pnl,"🔄 Auto Server Hop",false)); add(btn(pnl,"📊 Discord Webhook Stats",function() end))
elseif tab == "KILLER" then add(tog(pnl,"🧱 Block Pallet",false)); add(tog(pnl,"🪟 Block Window",false)); add(tog(pnl,"🔄 Counter Auto Parry",false)); add(tog(pnl,"🔱 Silent Aim Veil Spear V2",false)); add(tog(pnl,"🔮 Predict Silent Veil",false)); add(sld(pnl,"🎯 Silent TOF Prediction",0,100,50)); add(tog(pnl,"🎯 Auto Predict Target",false)); add(tog(pnl,"🏹 Auto Dodge Spear",false)); add(sld(pnl,"📏 Lead Multiplier",0.1,2.0,0.8)); add(tog(pnl,"👁️ ESP Tracker Target",false)); add(tog(pnl,"🎯 Aimbot Killer",false)); add(tog(pnl,"💀 Auto Kill All",false)); add(tog(pnl,"🔒 Aim Lock Toggle",false)); add(tog(pnl,"🎥 Third-Person Killer",false)); add(tog(pnl,"⏳ Anti Cooldown Stalker",false)); add(tog(pnl,"🐢 Anti Slowdown Killer",false)); add(tog(pnl,"📋 Perks Killer Info",false))
elseif tab == "ESP" then add(tog(pnl,"👤 ESP Survivor",false)); add(tog(pnl,"👹 ESP Killer",false)); add(tog(pnl,"🧟 ESP Zombie (SCP)",false)); add(tog(pnl,"⚡ ESP Generator",false)); add(tog(pnl,"🪝 ESP Hook",false)); add(tog(pnl,"🚪 ESP Gate",false)); add(tog(pnl,"🪵 ESP Pallet",false)); add(tog(pnl,"🪟 ESP Window",false)); add(tog(pnl,"🏷️ ESP Name",false)); add(tog(pnl,"📏 ESP Distance",false)); add(tog(pnl,"⚠️ Killer Warning",false)); add(tog(pnl,"🔮 Next Killer Display",false))
elseif tab == "UTILITY" then add(tog(pnl,"🎯 Crosshair",true)); add(tog(pnl,"💬 Global Chat GUI",false)); add(tog(pnl,"🎭 Player Emote",false)); add(btn(pnl,"✏️ Edit Attributes (Level/Gears/Screws)",function() end)); add(tog(pnl,"♾️ Unlimited Vault",false)); add(sld(pnl,"🎮 FPS Cap",30,240,60)); add(btn(pnl,"🌀 Teleport Players",function() end)); add(btn(pnl,"🔄 Refresh Map Cache",function() end)); add(tog(pnl,"🎭 Streamer Mode (Hide Name)",false)); add(tog(pnl,"💤 Anti AFK",true)); add(btn(pnl,"🔄 Rejoin Server",function() end)); add(tog(pnl,"📊 Hook Counter",false)); add(tog(pnl,"🔊 Hit Sound Effect",false)); add(btn(pnl,"⏹️ Unload Script",function() s:Destroy() end))
elseif tab == "MOVEMENT" then add(sld(pnl,"💨 Speed Boost",1,5,1.5,function(v) if p.Character and p.Character:FindFirstChild("Humanoid") then p.Character.Humanoid.WalkSpeed = 16*v end end)); add(tog(pnl,"⌨️ Speed Input Mode",false)); add(tog(pnl,"🏃 Auto Run (Mobile)",false)); add(tog(pnl,"🌀 No Clip",false)); add(tog(pnl,"🪂 No Fall Damage",true)); add(tog(pnl,"🔄 Infinite Jump",false)); add(tog(pnl,"⬆️ Force Jump",false)); add(tog(pnl,"🕊️ Fly GUI",false)); add(tog(pnl,"🌙 Moonwalk GUI",false)); add(tog(pnl,"👻 Invisible FE",false)); add(tog(pnl,"🤝 Can Interaction",false))
elseif tab == "VISUAL" then add(tog(pnl,"☀️ Full Bright",true,function(s) if s then game.Lighting.Brightness = 2; game.Lighting.Ambient = Color3.fromRGB(255,255,255) else game.Lighting.Brightness = 0.5 end end)); add(sld(pnl,"🌅 Time Of Day",0,24,12,function(v) game.Lighting:SetMinutesAfterMidnight(v*60) end)); add(tog(pnl,"🌫️ No Fog",true,function(s) game.Lighting.FogEnd = s and 99999 or 1000 end)); add(tog(pnl,"🌑 No Shadow",false)); add(tog(pnl,"📉 Low Graphics",false)); add(sld(pnl,"🔭 Infinity Zoom Out",1,10,1,function(v) if workspace.CurrentCamera then workspace.CurrentCamera.FieldOfView = 70/v end end)); add(sld(pnl,"📷 Camera FOV",1,120,70,function(v) if workspace.CurrentCamera then workspace.CurrentCamera.FieldOfView = v end end)); add(tog(pnl,"🎥 Third-Person Camera",false)); add(tog(pnl,"⏭️ Skip Endscreen",true)); add(tog(pnl,"🌀 Korless (Visual)",false)) end
cache[tab] = items; for _,item in ipairs(items) do item.Parent = pnl end; pnl.CanvasSize = UDim2.new(0,0,0,lay.AbsoluteContentSize.Y+20) end
update("SURVIVOR")
p.Idled:Connect(function() game:GetService("VirtualInputManager"):SendKeyEvent(true, Enum.KeyCode.W, false, game); game:GetService("VirtualInputManager"):SendKeyEvent(false, Enum.KeyCode.W, false, game) end)
r.Heartbeat:Connect(function() if p.Character and p.Character:FindFirstChild("Humanoid") then local h = p.Character.Humanoid; if h:GetState() == Enum.HumanoidStateType.FallingDown then h:ChangeState(Enum.HumanoidStateType.Jumping) end end end)
spawn(function() while wait(300) do pcall(function() local nv = game:HttpGet("https://raw.githubusercontent.com/zixster/violence/main/version.txt"); if nv and nv ~= "v3.0" then print("ZIXSTER: New version - "..nv) end end) end end)
print("✅ ZIXSTER v3.0 LOADED | github.com/zixster/violence")
